const FETCH_USER_REQ = "FETCH_USER_REQ";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
const REMOVE_USER = "REMOVE_USER";

export { FETCH_USER_FAILURE, FETCH_USER_REQ, FETCH_USER_SUCCESS, REMOVE_USER };
